ANMProject/src/objects/In_Sync_Biling__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>In Sync Bilings</relationshipLabel>
        <relationshipName>In_Sync_Bilings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Accuracy__c</fullName>
        <label>Billing Accuracy</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Latitude__c</fullName>
        <label>Billing Latitude</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Billing_Longitude_Code__c</fullName>
        <label>Billing Longitude Code</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Billing_Postal_Code__c</fullName>
        <label>Billing Postal Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <label>Billing State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Street__c</fullName>
        <label>Billing Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>In Sync Biling</label>
    <nameField>
        <label>In Sync Biling</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>In Sync Bilings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ANMProject/src/objects/In_Sync_Shipping__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>In Sync Shippings</relationshipLabel>
        <relationshipName>In_Sync_Shippings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipping_Accuracy__c</fullName>
        <label>Shipping Accuracy</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_City__c</fullName>
        <label>Shipping City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Country__c</fullName>
        <label>Shipping Country</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Latitude__c</fullName>
        <label>Shipping Latitude</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipping_Longitude_Code__c</fullName>
        <label>Shipping Longitude Code</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipping_Postal_Code__c</fullName>
        <label>Shipping Postal Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_State__c</fullName>
        <label>Shipping State</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Street__c</fullName>
        <label>Shipping Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>In Sync Shipping</label>
    <nameField>
        <label>In Sync Shipping</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>In Sync Shippings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ANMProject/src/classes/AddAccountList.cls
/**
 * Created by Donato on 3/2/18
 */

public class AddAccountList {
    // Function to set Map with Id, and Billing Record
    public static Map<Id, In_Sync_Biling__c> getAccIdToInSyncBilingMap(List<In_Sync_Biling__c> billingRecords){
        Map<Id, In_Sync_Biling__c> accIdToInSyncBilingMap = new Map<Id, In_Sync_Biling__c>();
        for(In_Sync_Biling__c billingRecord : billingRecords){
            accIdToInSyncBilingMap.put(billingRecord.Account__c, billingRecord);
        }
        return accIdToInSyncBilingMap;
    }
    // Function to set Map with Id, and Shipping Record
    public static Map<Id, In_Sync_Shipping__c> getAccIdToInSyncShippingMap(List<In_Sync_Shipping__c> shippingRecords){
        Map<Id, In_Sync_Shipping__c> accIdToInSyncShippingMap = new Map<Id, In_Sync_Shipping__c>();
        for(In_Sync_Shipping__c shippingRecord : shippingRecords){
            accIdToInSyncShippingMap.put(shippingRecord.Account__c, shippingRecord);
        }
        return accIdToInSyncShippingMap;
    }
    //Function to Change the updated Fields in Billings
    public static List<In_Sync_Biling__c> getBilingRecordsToUpdate(List<Account> accs, Map<Id, In_Sync_Biling__c> billingRecordsMap){
        List<In_Sync_Biling__c> bilingRecordToUpdate = new List<In_Sync_Biling__c>();
        for(Account acc : accs){
            // There has to be an IF for each field, to check every field exactly
            In_Sync_Biling__c billingRecordUpdated = billingRecordsMap.get(acc.Id);
            if(acc.BillingStreet != billingRecordUpdated.Billing_Street__c){
                billingRecordUpdated.Billing_Street__c = acc.BillingStreet;
            }
            if(acc.BillingCity != billingRecordUpdated.Billing_City__c){
                billingRecordUpdated.Billing_City__c = acc.BillingCity;
            }
            if(acc.BillingState != billingRecordUpdated.Billing_State__c){
                billingRecordUpdated.Billing_State__c = acc.BillingState;
            }
            if(acc.BillingPostalCode != billingRecordUpdated.Billing_Postal_Code__c){
                billingRecordUpdated.Billing_Postal_Code__c = acc.BillingPostalCode;
            }
            if(acc.BillingCountry != billingRecordUpdated.Billing_Country__c){
                billingRecordUpdated.Billing_Country__c = acc.BillingCountry;
            }
            if(acc.BillingLatitude != billingRecordUpdated.Billing_Latitude__c){
                billingRecordUpdated.Billing_Latitude__c = acc.BillingLatitude;
            }
            if(acc.BillingLongitude != billingRecordUpdated.Billing_Longitude_Code__c){
                billingRecordUpdated.Billing_Longitude_Code__c = acc.BillingLongitude;
            }
            if(acc.BillingGeocodeAccuracy != billingRecordUpdated.Billing_Accuracy__c) {
                billingRecordUpdated.Billing_Accuracy__c = acc.BillingGeocodeAccuracy;
            }
            bilingRecordToUpdate.add(billingRecordUpdated);
        }
        return bilingRecordToUpdate;
    }
    //Function to Change the updated Fields in Shippings
    public static List<In_Sync_Shipping__c> getShippingRecordsToUpdate(List<Account> accs, Map<Id, In_Sync_Shipping__c> shippingRecordsMap){
        List<In_Sync_Shipping__c> shippingRecordToUpdate = new List<In_Sync_Shipping__c>();
        for(Account acc : accs){
            // There has to be an IF for each field, to check every field exactly
            In_Sync_Shipping__c shippingRecordUpdate = shippingRecordsMap.get(acc.Id);
            if(acc.ShippingStreet != shippingRecordUpdate.Shipping_Street__c){
                shippingRecordUpdate.Shipping_Street__c = acc.ShippingStreet;
            }
            if(acc.ShippingCity != shippingRecordUpdate.Shipping_City__c){
                shippingRecordUpdate.Shipping_City__c = acc.ShippingCity;
            }
            if(acc.ShippingState != shippingRecordUpdate.Shipping_State__c){
                shippingRecordUpdate.Shipping_State__c = acc.ShippingState;
            }
            if(acc.ShippingPostalCode != shippingRecordUpdate.Shipping_Postal_Code__c){
                shippingRecordUpdate.Shipping_Postal_Code__c = acc.ShippingPostalCode;
            }
            if(acc.ShippingCountry != shippingRecordUpdate.Shipping_Country__c){
                shippingRecordUpdate.Shipping_Country__c = acc.ShippingCountry;
            }
            if(acc.ShippingLatitude != shippingRecordUpdate.Shipping_Latitude__c){
                shippingRecordUpdate.Shipping_Latitude__c = acc.ShippingLatitude;
            }
            if(acc.ShippingLongitude != shippingRecordUpdate.Shipping_Longitude_Code__c){
                shippingRecordUpdate.Shipping_Longitude_Code__c = acc.ShippingLongitude;
            }
            if(acc.ShippingGeocodeAccuracy != shippingRecordUpdate.Shipping_Accuracy__c) {
                shippingRecordUpdate.Shipping_Accuracy__c = acc.ShippingGeocodeAccuracy;
            }
            shippingRecordToUpdate.add(shippingRecordUpdate);
        }
        return shippingRecordToUpdate;
    }
}